import { randomUUID } from "node:crypto";
import express from "express";
import {
  buildHealthForwardPromise,
  commitmentForHealthPromise,
  decodeHealthForwardTask,
  encodeHealthCommitment,
  executeHealthForwardObservedTask,
  healthCommitmentFromTerms,
  type HealthForwardTask,
} from "./g5HealthForwardObserved.js";
import { clampPrice, jobSpec, listPrice, signQuote, submitResult, verifySignedJob } from "./signing.js";

const PORT = Number(process.env.AGENT_PORT || 9000);
function dataFromRpc(body: unknown): Record<string, unknown> { if(!body||typeof body!=="object"||Array.isArray(body))return{};const p=(body as Record<string,unknown>).params;if(!p||typeof p!=="object"||Array.isArray(p))return{};const m=(p as Record<string,unknown>).message;if(!m||typeof m!=="object"||Array.isArray(m))return{};const parts=(m as Record<string,unknown>).parts;if(!Array.isArray(parts))return{};for(const part of parts){if(part&&typeof part==="object"&&!Array.isArray(part)){const q=part as Record<string,unknown>;if(q.kind==="data"&&q.data&&typeof q.data==="object"&&!Array.isArray(q.data))return q.data as Record<string,unknown>;}}return{};}
function rpcReply(id:unknown,data:Record<string,unknown>){return{jsonrpc:"2.0",id:id??1,result:{kind:"message",role:"agent",messageId:randomUUID(),parts:[{kind:"data",data}]}};}
function taskFromData(data:Record<string,unknown>):HealthForwardTask|null{const direct=decodeHealthForwardTask(data.task_description);if(direct)return direct;const request=data.request;if(request&&typeof request==="object"&&!Array.isArray(request))return decodeHealthForwardTask((request as Record<string,unknown>).task_description);return null;}
async function preview(data:Record<string,unknown>){const task=taskFromData(data);if(!task)return{status:"rejected",error:"expected spondee.health-forward-observed.task.v1"};if(clampPrice(listPrice())!==0n)return{status:"rejected",error:"G5 observed proof requires zero service price"};return{status:"ok",promise:buildHealthForwardPromise(task,"0")};}
async function negotiate(data:Record<string,unknown>){const task=taskFromData(data);if(!task)return{status:"rejected",error:"expected spondee.health-forward-observed.task.v1"};if(clampPrice(listPrice())!==0n)return{status:"rejected",error:"G5 observed proof requires zero service price"};const request0=data.request&&typeof data.request==="object"&&!Array.isArray(data.request)?data.request as Record<string,unknown>:{task_description:data.task_description,terms:data.terms??{}};const promise=buildHealthForwardPromise(task,"0");const terms0=request0.terms&&typeof request0.terms==="object"&&!Array.isArray(request0.terms)?request0.terms as Record<string,unknown>:{};const criteria=Array.isArray(terms0.success_criteria)?terms0.success_criteria.filter((x):x is string=>typeof x==="string"&&!x.startsWith("SPONDEE_G5_HEALTH_FORWARD_COMMITMENT_V1:")):[];const request={...request0,task_description:data.task_description??request0.task_description,terms:{...terms0,success_criteria:[...criteria,encodeHealthCommitment(promise)]}};return signQuote(request,0n);}
async function notifyFunded(data:Record<string,unknown>){if(data.wait_for_result!==true)return{status:"rejected",error:"G5 Health evidence requires bounded wait_for_result=true"};let jobId:number;try{jobId=Number(BigInt(String(data.job_id??"")));}catch{return{status:"rejected",error:"invalid job_id"};}if(!Number.isSafeInteger(jobId)||jobId<=0)return{status:"rejected",error:"invalid job_id"};const verdict=await verifySignedJob(jobId);if(!verdict.ok)return{status:"rejected",job_id:jobId,error:verdict.reason,permanent:verdict.permanent};const spec=await jobSpec(jobId);if(!spec)return{status:"rejected",job_id:jobId,error:"missing structured job spec"};const task=decodeHealthForwardTask(spec.task);if(!task)return{status:"rejected",job_id:jobId,error:"job is not a G5 Health forward observed task"};const commitment=healthCommitmentFromTerms(spec.terms);if(!commitment)return{status:"rejected",job_id:jobId,error:"missing unique G5 Health commitment"};const promise=buildHealthForwardPromise(task,"0");const expected=commitmentForHealthPromise(promise);if(JSON.stringify(commitment)!==JSON.stringify(expected))return{status:"rejected",job_id:jobId,error:"G5 Health Promise commitment mismatch"};const output=await executeHealthForwardObservedTask(task);const submitted=await submitResult(jobId,JSON.stringify(output,null,2),{schema:"spondee.g5-health-forward-observed-metadata.v1",scenario_id:task.scenario_id,promise_id:promise.promise_id,evidence_class:"OBSERVED",market_data_execution:"READ_ONLY_BSC_MAINNET_CHAINLINK",mainnet_value_moved:false,liquidation_prevention_claimed:false});return{ok:true,job_id:jobId,tx_hash:submitted.submitTx,deliverable_url:submitted.deliverableUrl,promise_id:promise.promise_id,observation_started_at:output.observation_started_at,observation_completed_at:output.observation_completed_at,observed_round_count:output.rounds.length,warning_lead_time_seconds:output.event_tape.warning_lead_time_seconds};}
export async function dispatchG5HealthForwardSkill(data:Record<string,unknown>):Promise<Record<string,unknown>>{if(data.skill==="g5_health_forward_preview")return preview(data);if(data.skill==="negotiate")return negotiate(data);if(data.skill==="notify_funded")return notifyFunded(data);return{status:"rejected",error:`unknown skill: ${String(data.skill??"missing")}`};}
export function buildG5HealthForwardApp(){const app=express();app.use(express.json({limit:"256kb"}));app.get("/ping",(_req,res)=>res.json({status:"HEALTHY",mode:"G5_HEALTH_FORWARD_OBSERVED"}));app.post("/",async(req,res)=>{const id=req.body?.id;try{const result=await dispatchG5HealthForwardSkill(dataFromRpc(req.body));res.json(rpcReply(id,result));}catch(error){res.status(500).json({jsonrpc:"2.0",id:id??1,error:{code:-32603,message:error instanceof Error?error.message:"seller failure"}});}});return app;}
if(import.meta.url===`file://${process.argv[1]?.replaceAll("\\","/")}`||process.argv[1]?.endsWith("g5HealthForwardServer.ts")){buildG5HealthForwardApp().listen(PORT,"127.0.0.1",()=>console.log(`[g5-health-forward-seller] serving on 127.0.0.1:${PORT}`));}
