import { randomUUID } from "node:crypto";
import express from "express";
import {
  buildRebalancingForwardPromise,
  commitmentForRebalancingPromise,
  decodeRebalancingForwardTask,
  encodeRebalancingCommitment,
  executeRebalancingForwardObservedTask,
  rebalancingCommitmentFromTerms,
  type RebalancingForwardTask,
} from "./g5RebalancingForwardObserved.js";
import { clampPrice, jobSpec, listPrice, signQuote, submitResult, verifySignedJob } from "./signing.js";

const PORT=Number(process.env.AGENT_PORT||9000);
function dataFromRpc(body:unknown):Record<string,unknown>{if(!body||typeof body!=="object"||Array.isArray(body))return{};const p=(body as Record<string,unknown>).params;if(!p||typeof p!=="object"||Array.isArray(p))return{};const m=(p as Record<string,unknown>).message;if(!m||typeof m!=="object"||Array.isArray(m))return{};const parts=(m as Record<string,unknown>).parts;if(!Array.isArray(parts))return{};for(const part of parts){if(part&&typeof part==="object"&&!Array.isArray(part)){const q=part as Record<string,unknown>;if(q.kind==="data"&&q.data&&typeof q.data==="object"&&!Array.isArray(q.data))return q.data as Record<string,unknown>;}}return{};}
function rpcReply(id:unknown,data:Record<string,unknown>){return{jsonrpc:"2.0",id:id??1,result:{kind:"message",role:"agent",messageId:randomUUID(),parts:[{kind:"data",data}]}};}
function taskFromData(data:Record<string,unknown>):RebalancingForwardTask|null{const direct=decodeRebalancingForwardTask(data.task_description);if(direct)return direct;const request=data.request;if(request&&typeof request==="object"&&!Array.isArray(request))return decodeRebalancingForwardTask((request as Record<string,unknown>).task_description);return null;}
async function preview(data:Record<string,unknown>){const task=taskFromData(data);if(!task)return{status:"rejected",error:"expected spondee.rebalancing-forward-observed.task.v1"};if(clampPrice(listPrice())!==0n)return{status:"rejected",error:"G5 observed proof requires zero service price"};return{status:"ok",promise:buildRebalancingForwardPromise(task,"0")};}
async function negotiate(data:Record<string,unknown>){const task=taskFromData(data);if(!task)return{status:"rejected",error:"expected spondee.rebalancing-forward-observed.task.v1"};if(clampPrice(listPrice())!==0n)return{status:"rejected",error:"G5 observed proof requires zero service price"};const request0=data.request&&typeof data.request==="object"&&!Array.isArray(data.request)?data.request as Record<string,unknown>:{task_description:data.task_description,terms:data.terms??{}};const promise=buildRebalancingForwardPromise(task,"0");const terms0=request0.terms&&typeof request0.terms==="object"&&!Array.isArray(request0.terms)?request0.terms as Record<string,unknown>:{};const criteria=Array.isArray(terms0.success_criteria)?terms0.success_criteria.filter((x):x is string=>typeof x==="string"&&!x.startsWith("SPONDEE_G5_REBALANCING_FORWARD_COMMITMENT_V1:")):[];const request={...request0,task_description:data.task_description??request0.task_description,terms:{...terms0,success_criteria:[...criteria,encodeRebalancingCommitment(promise)]}};return signQuote(request,0n);}
async function notifyFunded(data:Record<string,unknown>){if(data.wait_for_result!==true)return{status:"rejected",error:"G5 Rebalancing evidence requires bounded wait_for_result=true"};let jobId:number;try{jobId=Number(BigInt(String(data.job_id??"")));}catch{return{status:"rejected",error:"invalid job_id"};}if(!Number.isSafeInteger(jobId)||jobId<=0)return{status:"rejected",error:"invalid job_id"};const verdict=await verifySignedJob(jobId);if(!verdict.ok)return{status:"rejected",job_id:jobId,error:verdict.reason,permanent:verdict.permanent};const spec=await jobSpec(jobId);if(!spec)return{status:"rejected",job_id:jobId,error:"missing structured job spec"};const task=decodeRebalancingForwardTask(spec.task);if(!task)return{status:"rejected",job_id:jobId,error:"job is not a G5 Rebalancing forward observed task"};const commitment=rebalancingCommitmentFromTerms(spec.terms);if(!commitment)return{status:"rejected",job_id:jobId,error:"missing unique G5 Rebalancing commitment"};const promise=buildRebalancingForwardPromise(task,"0");const expected=commitmentForRebalancingPromise(promise);if(JSON.stringify(commitment)!==JSON.stringify(expected))return{status:"rejected",job_id:jobId,error:"G5 Rebalancing Promise commitment mismatch"};const output=await executeRebalancingForwardObservedTask(task);const submitted=await submitResult(jobId,JSON.stringify(output,null,2),{schema:"spondee.g5-rebalancing-forward-observed-metadata.v1",scenario_id:task.scenario_id,promise_id:promise.promise_id,evidence_class:"OBSERVED",market_data_execution:"READ_ONLY_BSC_MAINNET_CHAINLINK",mainnet_value_moved:false,realized_mainnet_pnl_claimed:false});return{ok:true,job_id:jobId,tx_hash:submitted.submitTx,deliverable_url:submitted.deliverableUrl,promise_id:promise.promise_id,observation_started_at:output.observation_started_at,observation_completed_at:output.observation_completed_at,observed_round_count:output.rounds.length};}
export async function dispatchG5RebalancingForwardSkill(data:Record<string,unknown>):Promise<Record<string,unknown>>{if(data.skill==="g5_rebalancing_forward_preview")return preview(data);if(data.skill==="negotiate")return negotiate(data);if(data.skill==="notify_funded")return notifyFunded(data);return{status:"rejected",error:`unknown skill: ${String(data.skill??"missing")}`};}
export function buildG5RebalancingForwardApp(){const app=express();app.use(express.json({limit:"256kb"}));app.get("/ping",(_req,res)=>res.json({status:"HEALTHY",mode:"G5_REBALANCING_FORWARD_OBSERVED"}));app.post("/",async(req,res)=>{const id=req.body?.id;try{const result=await dispatchG5RebalancingForwardSkill(dataFromRpc(req.body));res.json(rpcReply(id,result));}catch(error){res.status(500).json({jsonrpc:"2.0",id:id??1,error:{code:-32603,message:error instanceof Error?error.message:"seller failure"}});}});return app;}
if(import.meta.url===`file://${process.argv[1]?.replaceAll("\\","/")}`||process.argv[1]?.endsWith("g5RebalancingForwardServer.ts")){buildG5RebalancingForwardApp().listen(PORT,"127.0.0.1",()=>console.log(`[g5-rebalancing-forward-seller] serving on 127.0.0.1:${PORT}`));}
