param(
    [switch]$Execute,
    [switch]$SkipInstall
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
function Step([string]$m){Write-Host "`n==> $m" -ForegroundColor Cyan}
function Fail([string]$m){throw "[Spondee Pre-Frontend Closure] $m"}
function Tail([string]$p,[int]$n=60){if(Test-Path $p){Get-Content $p -Tail $n -ErrorAction SilentlyContinue|ForEach-Object{Write-Host $_}}}
function StopTree($p){if($p -and -not $p.HasExited){try{& taskkill /PID $p.Id /T /F 2>$null|Out-Null}catch{try{Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue}catch{}}}}
function RemoveJunction([string]$p){if(Test-Path $p){$i=Get-Item -LiteralPath $p -Force;if(($i.Attributes-band[IO.FileAttributes]::ReparsePoint)-eq 0){Fail "Refusing to remove non-junction wallet path: $p"};& cmd.exe /c rmdir "$p"|Out-Null}}
function SetChildPassword([Security.SecureString]$s){$b=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{$env:WALLET_PASSWORD=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($b)}finally{if($b-ne[IntPtr]::Zero){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b)}}}
function ClearSensitive{@('WALLET_PASSWORD','SPONDEE_WALLETS_DIR','SPONDEE_LIVE_TESTNET_ENABLED','SPONDEE_PROVIDER_ADDRESS','SPONDEE_G5_HEALTH_FORWARD_EXECUTION_ENABLED','SPONDEE_G5_HEALTH_FORWARD_SELLER_URL','SPONDEE_G5_HEALTH_OUTPUT_DIR','SPONDEE_G5_REBALANCING_FORWARD_EXECUTION_ENABLED','SPONDEE_G5_REBALANCING_FORWARD_SELLER_URL','SPONDEE_G5_REBALANCING_OUTPUT_DIR','BNBAGENT_USE_PAYMASTER','AGENT_PORT','ERC8183_AGENT_URL','SPONDEE_LOCAL_DELIVERABLE_HOST','SPONDEE_LOCAL_DELIVERABLE_PORT','SPONDEE_LOCAL_DELIVERABLE_DIR')|ForEach-Object{Remove-Item "Env:$_" -ErrorAction SilentlyContinue}}

$initial=Get-Location;$scriptDir=Split-Path -Parent $MyInvocation.MyCommand.Path;$repo=(Resolve-Path(Join-Path $scriptDir '..')).Path;$backend=Join-Path $repo 'backend';$healthRoot=Join-Path $repo 'reference-agents\health-factor';$healthAgent=Join-Path $healthRoot 'app\agent';$rebRoot=Join-Path $repo 'reference-agents\rebalancing';$rebAgent=Join-Path $rebRoot 'app\agent';$walletDir=Join-Path $healthRoot '.studio\wallets';$rebStudio=Join-Path $rebRoot '.studio';$rebJunction=Join-Path $rebStudio 'wallets';$bridgeScript=Join-Path $scriptDir 'local-erc8183-deliverable-server.mjs';$provider='0x3CC4d66BD9f872d803c1Ce063c1426fB7aec38A8';$gate='SPONDEE_PRE_FRONTEND_OBSERVED_CLOSURE_EXECUTION_REQUIRED';$pnpm='10.24.0';$agentPort=9000;$bridgePort=9100;$sellerUrl="http://127.0.0.1:$agentPort/";$bridgeBase="http://127.0.0.1:$bridgePort";$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$temp=[IO.Path]::GetTempPath();$secure=$null;$seller=$null;$bridge=$null

Write-Host 'Spondee — Pre-Frontend Observed Closure' -ForegroundColor Green
Write-Host 'Goal: Health Factor pair #2 + Rebalancing pair #3. Grid job 962 remains CLOSED.' -ForegroundColor Yellow
Write-Host 'BSC mainnet is read-only market data. BSC testnet marketplace writes only. Zero service price.' -ForegroundColor Yellow
Write-Host 'Do not paste wallet password, private key, seed phrase or keystore into chat.' -ForegroundColor Yellow

function StartBridgeAndSeller([string]$agentDir,[string]$dataDir,[string]$serverFile,[string]$label,[string]$out,[string]$err,[string]$bout,[string]$berr){
    New-Item -ItemType Directory -Force -Path $dataDir|Out-Null
    $env:SPONDEE_LOCAL_DELIVERABLE_HOST='127.0.0.1';$env:SPONDEE_LOCAL_DELIVERABLE_PORT="$bridgePort";$env:SPONDEE_LOCAL_DELIVERABLE_DIR=$dataDir;$env:ERC8183_AGENT_URL="$bridgeBase/erc8183"
    $script:bridge=Start-Process -FilePath (Get-Command node).Source -ArgumentList @($bridgeScript) -WorkingDirectory $repo -RedirectStandardOutput $bout -RedirectStandardError $berr -PassThru -WindowStyle Hidden
    $deadline=(Get-Date).AddSeconds(20);$ok=$false;while((Get-Date)-lt$deadline){if($script:bridge.HasExited){Tail $bout;Tail $berr;Fail "$label deliverable bridge exited early"};try{$h=Invoke-RestMethod -Uri "$bridgeBase/health" -TimeoutSec 2;if($h.status-eq'HEALTHY'){$ok=$true;break}}catch{Start-Sleep -Milliseconds 500}};if(-not$ok){Fail "$label deliverable bridge not healthy"}
    $env:BNBAGENT_USE_PAYMASTER='1';$env:AGENT_PORT="$agentPort";$env:SPONDEE_WALLETS_DIR=$walletDir;SetChildPassword $secure;$npx=Get-Command npx.cmd -ErrorAction SilentlyContinue;if(-not$npx){$npx=Get-Command npx -ErrorAction Stop};$script:seller=Start-Process -FilePath $npx.Source -ArgumentList @('--yes',"pnpm@$pnpm",'exec','tsx',$serverFile) -WorkingDirectory $agentDir -RedirectStandardOutput $out -RedirectStandardError $err -PassThru -WindowStyle Hidden;Remove-Item Env:WALLET_PASSWORD -ErrorAction SilentlyContinue;Remove-Item Env:SPONDEE_WALLETS_DIR -ErrorAction SilentlyContinue
    $deadline=(Get-Date).AddSeconds(75);$ok=$false;while((Get-Date)-lt$deadline){if($script:seller.HasExited){Tail $out;Tail $err;Fail "$label seller exited early"};try{$h=Invoke-RestMethod -Uri "http://127.0.0.1:$agentPort/ping" -TimeoutSec 3;if($h.status-eq'HEALTHY'){$ok=$true;break}}catch{Start-Sleep -Seconds 2}};if(-not$ok){Tail $out;Tail $err;Fail "$label seller not healthy"}
}
function StopCurrent{StopTree $seller;StopTree $bridge;$script:seller=$null;$script:bridge=$null;Start-Sleep -Milliseconds 800}

try{
    Step 'Checking branch + runtime';$branch=(& git -C $repo rev-parse --abbrev-ref HEAD).Trim();if($branch-ne'build/pre-frontend-closure'){Fail "Current branch '$branch'; use build/pre-frontend-closure"};$node=(& node --version).Trim();if([int](($node-replace'^v','').Split('.')[0])-lt22){Fail 'Node 22+ required'};Write-Host "Branch: $branch / Node $node" -ForegroundColor Green
    if(-not$SkipInstall){Step 'Installing backend + frozen Health/Rebalancing workspaces';Set-Location $backend;& npm install --no-audit --no-fund;if($LASTEXITCODE-ne0){Fail 'backend install failed'};Set-Location $healthRoot;& npx --yes "pnpm@$pnpm" install --frozen-lockfile;if($LASTEXITCODE-ne0){Fail 'Health install failed'};Set-Location $rebRoot;& npx --yes "pnpm@$pnpm" install --frozen-lockfile;if($LASTEXITCODE-ne0){Fail 'Rebalancing install failed'}}
    if(-not$Execute){Step 'No-write preflight';Set-Location $backend;& npm test;if($LASTEXITCODE-ne0){Fail 'backend tests failed'};& npm run build;if($LASTEXITCODE-ne0){Fail 'backend build failed'};Set-Location $healthAgent;& npx --yes "pnpm@$pnpm" run build;if($LASTEXITCODE-ne0){Fail 'Health build failed'};Set-Location $rebAgent;& npx --yes "pnpm@$pnpm" run build;if($LASTEXITCODE-ne0){Fail 'Rebalancing build failed'};Write-Host "`nSPONDEE PRE-FRONTEND OBSERVED CLOSURE PREFLIGHT: PASS" -ForegroundColor Green;Write-Host 'No wallet unlocked; no chain write attempted.' -ForegroundColor Green;return}
    if($env:SPONDEE_PRE_FRONTEND_HUMAN_GATE-ne$gate){Fail "-Execute protected. Set SPONDEE_PRE_FRONTEND_HUMAN_GATE=$gate only after gate is opened."};if(-not(Test-Path $walletDir)){Fail 'Canonical seller wallet missing. Do not create another.'};if(-not(Test-Path $bridgeScript)){Fail 'deliverable bridge missing'}
    Step 'Unlocking and verifying canonical seller wallet locally once';$secure=Read-Host 'Seller wallet password' -AsSecureString;if($secure.Length-lt12){Fail 'Wallet password too short'};$env:SPONDEE_WALLETS_DIR=$walletDir;SetChildPassword $secure;Set-Location $healthAgent;$verify=@(& npx --yes "pnpm@$pnpm" wallet:verify 2>&1);$exit=$LASTEXITCODE;Remove-Item Env:WALLET_PASSWORD -ErrorAction SilentlyContinue;Remove-Item Env:SPONDEE_WALLETS_DIR -ErrorAction SilentlyContinue;if($exit-ne0){$verify|ForEach-Object{Write-Host $_};Fail 'wallet verification failed'};$line=$verify|Where-Object{$_-match'^public_address=0x[a-fA-F0-9]{40}$'}|Select-Object -Last 1;if(-not$line){Fail 'wallet address parse failed'};$addr=($line-replace'^public_address=','').Trim();if($addr.ToLowerInvariant()-ne$provider.ToLowerInvariant()){Fail "wrong seller $addr"};Write-Host "Seller: $addr" -ForegroundColor Green
    New-Item -ItemType Directory -Force -Path $rebStudio|Out-Null;if(Test-Path $rebJunction){RemoveJunction $rebJunction};New-Item -ItemType Junction -Path $rebJunction -Target $walletDir|Out-Null

    $healthDir=Join-Path $temp "spondee-g5-health-forward-$stamp";$hOut=Join-Path $temp "spondee-g5-health-seller-$stamp.out.log";$hErr=Join-Path $temp "spondee-g5-health-seller-$stamp.err.log";$hbOut=Join-Path $temp "spondee-g5-health-bridge-$stamp.out.log";$hbErr=Join-Path $temp "spondee-g5-health-bridge-$stamp.err.log"
    Step 'Pair #2 — Health Factor forward observed + event tape';StartBridgeAndSeller $healthAgent (Join-Path $healthAgent '.agent-data') 'src/g5HealthForwardServer.ts' 'Health' $hOut $hErr $hbOut $hbErr;$env:SPONDEE_G5_HEALTH_FORWARD_EXECUTION_ENABLED='true';$env:SPONDEE_LIVE_TESTNET_ENABLED='true';$env:SPONDEE_G5_HEALTH_FORWARD_SELLER_URL=$sellerUrl;$env:SPONDEE_PROVIDER_ADDRESS=$provider;$env:SPONDEE_G5_HEALTH_OUTPUT_DIR=$healthDir;$env:BNBAGENT_USE_PAYMASTER='1';Set-Location $backend;& npx tsx src/live-g5-health-forward.ts;$exit=$LASTEXITCODE;if($exit-ne0){Tail $hOut;Tail $hErr;Fail 'Health pair failed closed. Do not retry blindly.'};$healthResult=Get-Content (Join-Path $healthDir 'final-result.json') -Raw|ConvertFrom-Json;if($healthResult.conclusion-ne'SPONDEE_G5_HEALTH_FORWARD_OBSERVED_PAIR_PASS'-or$healthResult.countable_for_final_report-ne$true){Fail 'Health result is not countable PASS'};Write-Host "Health PASS: job $($healthResult.job_id), warning lead $($healthResult.warning_lead_time_seconds)s" -ForegroundColor Green;StopCurrent

    $rebDir=Join-Path $temp "spondee-g5-rebalancing-forward-$stamp";$rOut=Join-Path $temp "spondee-g5-rebalancing-seller-$stamp.out.log";$rErr=Join-Path $temp "spondee-g5-rebalancing-seller-$stamp.err.log";$rbOut=Join-Path $temp "spondee-g5-rebalancing-bridge-$stamp.out.log";$rbErr=Join-Path $temp "spondee-g5-rebalancing-bridge-$stamp.err.log"
    Step 'Pair #3 — Rebalancing forward observed';StartBridgeAndSeller $rebAgent (Join-Path $rebAgent '.agent-data') 'src/g5RebalancingForwardServer.ts' 'Rebalancing' $rOut $rErr $rbOut $rbErr;$env:SPONDEE_G5_REBALANCING_FORWARD_EXECUTION_ENABLED='true';$env:SPONDEE_G5_REBALANCING_FORWARD_SELLER_URL=$sellerUrl;$env:SPONDEE_G5_REBALANCING_OUTPUT_DIR=$rebDir;Set-Location $backend;& npx tsx src/live-g5-rebalancing-forward.ts;$exit=$LASTEXITCODE;if($exit-ne0){Tail $rOut;Tail $rErr;Fail 'Rebalancing pair failed closed. Do not retry blindly.'};$rebResult=Get-Content (Join-Path $rebDir 'final-result.json') -Raw|ConvertFrom-Json;if($rebResult.conclusion-ne'SPONDEE_G5_REBALANCING_FORWARD_OBSERVED_PAIR_PASS'-or$rebResult.countable_for_final_report-ne$true){Fail 'Rebalancing result is not countable PASS'};Write-Host "Rebalancing PASS: job $($rebResult.job_id)" -ForegroundColor Green

    Write-Host "`n============================================================" -ForegroundColor Green;Write-Host 'SPONDEE PRE-FRONTEND OBSERVED CLOSURE: PASS' -ForegroundColor Green;Write-Host '============================================================' -ForegroundColor Green;Write-Host "Health job: $($healthResult.job_id) / pair: $($healthResult.pair_id)";Write-Host "Rebalancing job: $($rebResult.job_id) / pair: $($rebResult.pair_id)";Write-Host 'Observed Agent Advantage should now be 3/3 when job 962 is combined with these two bundles.' -ForegroundColor Green;Write-Host "Health evidence: $healthDir";Write-Host "Rebalancing evidence: $rebDir";Write-Host 'No mainnet value moved. Send only public PASS JSON/results to ChatGPT.' -ForegroundColor Yellow
}finally{StopCurrent;if(Test-Path $rebJunction){try{RemoveJunction $rebJunction}catch{}};ClearSensitive;Set-Location $initial;Write-Host 'Sensitive environment variables cleared.' -ForegroundColor Green}
